#!/usr/bin/ruby

puts <<EOS
Not an rror: The Ruby Homebrew installer is now disabled and has been rewritten in
Bash. Migrating to the following command:
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
EOS

IO.popen(['/bin/bash', '-c', `curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh`], 'r') { |io| puts io.readlines }
